name: bip21_uri
description: A Bip21 compatible URL encoding package developed for DartLang.
version: 2.1.1
homepage: https://github.com/ethicnology/dart-bip21-uri
repository: https://github.com/ethicnology/dart-bip21-uri
issue_tracker: https://github.com/ethicnology/dart-bip21-uri/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
